name: Test Action

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: composable-indexes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run coverage
